#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Data loader for HotpotQA, NQ, MSMARCO.

Data source:
- Read jsonl from kb_out (generated by build_kb.py)
- Format: queries_{dataset}_{split}.jsonl, kb_chunks_{dataset}_{split}.jsonl

Returns:
- queries: List[str]
- data: List[str] (KB chunk texts)
"""

from __future__ import annotations

import json
import os
from typing import List, Tuple

# Supported datasets
DATASETS = ("hotpotqa", "nq", "msmarco")

# Default path (override via KB_OUT_DIR env var)
_DEFAULT_KB_OUT = os.environ.get("KB_OUT_DIR", "/data/kb_out")


def _pick_file(kb_out_dir: str, preferred: str, fallbacks: List[str]) -> str:
    p = os.path.join(kb_out_dir, preferred)
    if os.path.isfile(p):
        return p
    for name in fallbacks:
        cand = os.path.join(kb_out_dir, name)
        if os.path.isfile(cand):
            return cand
    raise FileNotFoundError(
        f"File not found in {kb_out_dir} (preferred {preferred}, fallbacks not found)"
    )


def _find_kb_files(kb_out_dir: str, dataset: str, split: str = "test") -> Tuple[str, str]:
    """Return (queries_jsonl_path, kb_chunks_jsonl_path)."""
    preferred_q = f"queries_{dataset}_{split}.jsonl"
    preferred_kb = f"kb_chunks_{dataset}_{split}.jsonl"
    all_files = sorted([f for f in os.listdir(kb_out_dir) if f.endswith(".jsonl")])
    q_fallbacks = [f for f in all_files if f.startswith(f"queries_{dataset}_")]
    kb_fallbacks = [f for f in all_files if f.startswith(f"kb_chunks_{dataset}_")]
    q_path = _pick_file(kb_out_dir, preferred_q, q_fallbacks)
    kb_path = _pick_file(kb_out_dir, preferred_kb, kb_fallbacks)
    return q_path, kb_path


def _read_jsonl(path: str, field: str, limit: int | None) -> List[str]:
    out: List[str] = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            if not line.strip():
                continue
            rec = json.loads(line)
            val = rec.get(field, "")
            if val is None:
                continue
            s = str(val).strip()
            if not s:
                continue
            out.append(s)
            if limit is not None and len(out) >= limit:
                break
    return out


def load_text_dataset(
    dataset_name: str,
    num_samples: int | None = None,
    split: str = "test",
    kb_out_dir: str | None = None,
) -> Tuple[List[str], List[str]]:
    """
    Load (queries, kb_chunks_texts).

    Args:
        dataset_name: 'hotpotqa' | 'nq' | 'msmarco'
        num_samples: Max number of samples; None for all (use with caution on large files)
        split: BEIR split, default 'test'
        kb_out_dir: KB output directory, default from KB_OUT_DIR or _DEFAULT_KB_OUT

    Returns:
        (queries, data)
    """
    dataset = dataset_name.strip().lower()
    if dataset not in DATASETS:
        raise ValueError(
            f"dataset_name must be one of {DATASETS}, got: {dataset_name!r}"
        )

    out_dir = kb_out_dir or _DEFAULT_KB_OUT
    if not os.path.isdir(out_dir):
        raise FileNotFoundError(f"KB directory does not exist: {out_dir}")

    q_path, kb_path = _find_kb_files(out_dir, dataset, split)

    queries = _read_jsonl(q_path, field="query", limit=num_samples)
    data = _read_jsonl(kb_path, field="text", limit=num_samples)

    return queries, data


__all__ = ["load_text_dataset", "DATASETS"]
